export const categories = [
  {
    name: "Plant-based foods and beverages",
    value: "plant-based-foods-and-beverages",
  },
  { name: "Plant-based foods", value: "plant-based-foods" },
  { name: "Snacks", value: "snacks" },
  { name: "Sweet snacks", value: "sweet-snacks" },
  { name: "Beverages", value: "beverages" },
  { name: "Dairies", value: "dairies" },
  { name: "Cereals and potatoes", value: "cereals-and-potatoes" },
  { name: "Meats and their products", value: "meats-and-their-products" },
  { name: "Fermented foods", value: "fermented-foods" },
  { name: "Fermented milk products", value: "fermented-milk-products" },
  {
    name: "Fruits and vegetables based foods",
    value: "fruits-and-vegetables-based-foods",
  },
  { name: "Condiments", value: "condiments" },
  { name: "Meats", value: "meats" },
  { name: "Desserts", value: "desserts" },
  { name: "Biscuits and cakes", value: "biscuits-and-cakes" },
  { name: "Meals", value: "meals" },
  { name: "Cereals and their products", value: "cereals-and-their-products" },
  { name: "Spreads", value: "spreads" },
  { name: "Cheeses", value: "cheeses" },
  { name: "Sauces", value: "sauces" },
  { name: "Confectioneries", value: "confectioneries" },
  { name: "Groceries", value: "groceries" },
  { name: "Frozen foods", value: "frozen-foods" },
  { name: "Breakfasts", value: "breakfasts" },
  { name: "Prepared meats", value: "prepared-meats" },
  { name: "Plant-based beverages", value: "plant-based-beverages" },
  { name: "Vegetables based foods", value: "vegetables-based-foods" },
  { name: "Cocoa and its products", value: "cocoa-and-its-products" },
  { name: "Canned foods", value: "canned-foods" },
  { name: "Seafood", value: "seafood" },
  { name: "Sweet spreads", value: "sweet-spreads" },
  { name: "Biscuits", value: "biscuits" },
  { name: "Fruits based foods", value: "fruits-based-foods" },
  { name: "Dairy desserts", value: "dairy-desserts" },
  { name: "Breads", value: "breads" },
  { name: "Plant-based spreads", value: "plant-based-spreads" },
  { name: "Fats", value: "fats" },
  { name: "Fermented dairy desserts", value: "fermented-dairy-desserts" },
  { name: "Fishes and their products", value: "fishes-and-their-products" },
  { name: "Salty snacks", value: "salty-snacks" },
  { name: "Fishes", value: "fishes" },
  { name: "Pastas", value: "pastas" },
  { name: "Alcoholic beverages", value: "alcoholic-beverages" },
  { name: "Poultries", value: "poultries" },
  { name: "Yogurts", value: "yogurts" },
  { name: "Sweeteners", value: "sweeteners" },
  { name: "Legumes and their products", value: "legumes-and-their-products" },
  { name: "Frozen desserts", value: "frozen-desserts" },
  { name: "Vegetable fats", value: "vegetable-fats" },
  { name: "Seeds", value: "seeds" },
  { name: "Appetizers", value: "appetizers" },
  {
    name: "Beverages and beverages preparations",
    value: "beverages-and-beverages-preparations",
  },
  { name: "Cakes", value: "cakes" },
  { name: "Canned plant-based foods", value: "canned-plant-based-foods" },
  { name: "Nuts and their products", value: "nuts-and-their-products" },
  { name: "Chocolates", value: "chocolates" },
  { name: "Farming products", value: "farming-products" },
  { name: "Vegetables", value: "vegetables" },
  { name: "Dried products", value: "dried-products" },
  { name: "Fruit-based beverages", value: "fruit-based-beverages" },
  { name: "Vegetable oils", value: "vegetable-oils" },
  { name: "Fatty fishes", value: "fatty-fishes" },
  { name: "Juices and nectars", value: "juices-and-nectars" },
  { name: "Dietary supplements", value: "dietary-supplements" },
  { name: "Hot beverages", value: "hot-beverages" },
  { name: "Chicken and its products", value: "chicken-and-its-products" },
  { name: "Breakfast cereals", value: "breakfast-cereals" },
  { name: "Chocolate candies", value: "chocolate-candies" },
  { name: "Bee products", value: "bee-products" },
  {
    name: "Fruit and vegetable preserves",
    value: "fruit-and-vegetable-preserves",
  },
  { name: "Carbonated drinks", value: "carbonated-drinks" },
  { name: "Legumes", value: "legumes" },
  { name: "Olive tree products", value: "olive-tree-products" },
  { name: "Honeys", value: "honeys" },
  { name: "Cow cheeses", value: "cow-cheeses" },
  { name: "Chickens", value: "chickens" },
  { name: "Candies", value: "candies" },
  { name: "Fruits", value: "fruits" },
  { name: "Chips and fries", value: "chips-and-fries" },
  { name: "Nuts", value: "nuts" },
  { name: "Hams", value: "hams" },
  { name: "Ice creams and sorbets", value: "ice-creams-and-sorbets" },
  { name: "Sodas", value: "sodas" },
  { name: "Crisps", value: "crisps" },
  { name: "Jams", value: "jams" },
  { name: "Fruit juices", value: "fruit-juices" },
  { name: "Salted spreads", value: "salted-spreads" },
  { name: "Milks", value: "milks" },
  { name: "Soups", value: "soups" },
  { name: "Canned vegetables", value: "canned-vegetables" },
  { name: "Sausages", value: "sausages" },
  { name: "Cereal grains", value: "cereal-grains" },
  { name: "Dairy substitutes", value: "dairy-substitutes" },
  { name: "Dried plant-based foods", value: "dried-plant-based-foods" },
  { name: "Teas", value: "teas" },
  { name: "Olive oils", value: "olive-oils" },
  { name: "Wines", value: "wines" },
  { name: "Meals with meat", value: "meals-with-meat" },
  { name: "Waters", value: "waters" },
  { name: "Pasta dishes", value: "pasta-dishes" },
];

export const productAndGradeSort = [
  {
    name: "Sort by Product Name A-Z",
    value: { item: "products", sort: "asc" },
  },
  {
    name: "Sort by Product Name Z-A",
    value: { item: "products", sort: "desc" },
  },
  { name: "Nutriscore A-E", value: { item: "grade", sort: "asc" } },
  { name: "Nutriscore E-A", value: { item: "grade", sort: "desc" } },
];
